[package]
name         = "cgp-core"
version      = "0.4.0"
edition      = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
authors      = { workspace = true }
rust-version = { workspace = true }
keywords     = { workspace = true }
description  = """
    Context-generic programming core traits
"""

[features]
default             = [ "full" ]
full                = [ "cgp-async/full" ]

[dependencies]
cgp-async           = { version = "0.4.0", default-features = false }
cgp-component       = { version = "0.4.0" }
cgp-macro           = { version = "0.4.0" }
cgp-type            = { version = "0.4.0" }
cgp-error           = { version = "0.4.0" }
cgp-field           = { version = "0.4.0" }