[workspace]

resolver = "2"

members = [
    "crates/cgp-async",
    "crates/cgp-sync",
    "crates/cgp-component",
    "crates/cgp-component-macro",
    "crates/cgp-error",
    "crates/cgp-strip-async",
]