[package]
name         = "cgp-extra"
version      = "0.2.0"
edition      = { workspace = true }
license      = { workspace = true }
repository   = { workspace = true }
authors      = { workspace = true }
rust-version = { workspace = true }
keywords     = { workspace = true }
description  = """
    Context-generic programming extra meta-crate
"""
[features]
default = [ "full" ]
full = [ "cgp-error-extra/alloc" ]

[dependencies]
cgp-error-extra = { version = "0.2.0", default-features = false }
cgp-inner       = { version = "0.2.0" }
cgp-run         = { version = "0.2.0" }
cgp-runtime     = { version = "0.2.0" }
